import { useState } from 'react';
import { AlertCircle, Clock, RefreshCw, Sparkles } from 'lucide-react';
import { useActiveProfile } from '@/context/ActiveProfileContext';
import { Card, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Select } from '@/components/ui/Select';
import { Badge } from '@/components/ui/Badge';
import { Loading } from '@/components/feedback/Loading';
import { useAISummary } from '@/hooks/useAISummary';
import { longDate } from '@/lib/health';

const PERIOD_OPTIONS = [
  { value: '7', label: 'Last 7 days' },
  { value: '14', label: 'Last 14 days' },
  { value: '30', label: 'Last 30 days' },
];

const RATE_LIMIT_MINUTES = 10;

export function AISummaryPage() {
  const { activeProfile } = useActiveProfile();
  const [days, setDays] = useState('7');
  const { result, loading, error, generate, reset } = useAISummary();

  if (!activeProfile) return <Loading label="Loading profile" />;

  function handleGenerate() {
    reset();
    generate(activeProfile!.id, Number(days));
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-neutral-900">AI health summary</h2>
        <p className="mt-1 text-sm text-neutral-600">
          A plain-language overview of {activeProfile.display_name}'s logged habits over a selected period.
        </p>
      </div>

      {/* Disclaimer — always visible */}
      <div className="flex items-start gap-3 rounded-xl border border-warning-200 bg-warning-50 px-4 py-3">
        <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-warning-600" />
        <p className="text-sm text-warning-800">
          <strong>Informational only.</strong> This summary describes patterns in your logged data.
          It is not medical advice, a diagnosis, or a treatment recommendation.
          Always consult a qualified healthcare professional for medical decisions.
        </p>
      </div>

      {/* Controls */}
      <Card>
        <div className="flex flex-wrap items-end gap-4">
          <Select
            label="Period"
            name="days"
            value={days}
            options={PERIOD_OPTIONS}
            onChange={(e) => setDays(e.target.value)}
          />
          <Button onClick={handleGenerate} loading={loading} disabled={loading}>
            <Sparkles className="h-4 w-4" />
            {result ? 'Regenerate' : 'Generate summary'}
          </Button>
        </div>
        <div className="mt-3 flex items-center gap-1.5 text-xs text-neutral-500">
          <Clock className="h-3.5 w-3.5" />
          <span>Summaries are generated by an AI model using only your logged data and can be requested once every {RATE_LIMIT_MINUTES} minutes.</span>
        </div>
      </Card>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-error-200 bg-error-50 px-4 py-3">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-error-600" />
          <div className="flex-1">
            <p className="text-sm font-medium text-error-800">Could not generate summary</p>
            <p className="mt-0.5 text-sm text-error-700">{error}</p>
          </div>
          <Button size="sm" variant="ghost" onClick={handleGenerate}>
            <RefreshCw className="h-4 w-4" />
            Retry
          </Button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <Card>
          <div className="flex flex-col items-center gap-3 py-8">
            <Sparkles className="h-8 w-8 animate-pulse text-primary-500" />
            <p className="text-sm text-neutral-600">Analysing {PERIOD_OPTIONS.find((o) => o.value === days)?.label.toLowerCase()}…</p>
          </div>
        </Card>
      )}

      {/* Result */}
      {result && !loading && (
        <Card>
          <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
            <CardHeader
              title="Summary"
              subtitle={`${longDate(result.period_start)} to ${longDate(result.period_end)}`}
            />
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="primary">AI generated</Badge>
              <Badge variant="neutral">{PERIOD_OPTIONS.find((o) => o.value === String(result.period_days))?.label}</Badge>
            </div>
          </div>

          <div className="prose prose-sm max-w-none">
            {result.summary.split('\n').filter(Boolean).map((para, i) => (
              <p key={i} className={para === result.disclaimer ? 'mt-4 text-xs text-neutral-500 italic' : 'text-sm leading-relaxed text-neutral-800'}>
                {para}
              </p>
            ))}
          </div>

          <div className="mt-5 flex items-center justify-between border-t border-neutral-100 pt-4">
            <p className="text-xs text-neutral-500">
              Generated from your logged check-ins, activities, and goals. The AI model never sees your documents or personal identifiers.
            </p>
            <Button size="sm" variant="outline" onClick={handleGenerate}>
              <RefreshCw className="h-3.5 w-3.5" />
              Regenerate
            </Button>
          </div>
        </Card>
      )}

      {/* Past summaries placeholder */}
      {!result && !loading && !error && (
        <Card>
          <div className="flex flex-col items-center gap-2 py-10 text-center">
            <Sparkles className="h-10 w-10 text-primary-200" />
            <p className="text-sm font-medium text-neutral-700">No summary generated yet</p>
            <p className="max-w-xs text-xs text-neutral-500">
              Select a period and click "Generate summary" to get an AI-written overview of your logged habits.
            </p>
          </div>
        </Card>
      )}
    </div>
  );
}
